// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(BazaDbContext))]
    [Migration("20260527201442_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("WebApplication1.Models.Film", b =>
                {
                    b.Property<int>("IdFilma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CijenaKupnje")
                        .HasColumnType("REAL");

                    b.Property<float>("CijenaRente")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("DatumRente")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdKupca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivFilma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rezervacija")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdFilma");

                    b.ToTable("filmovi");
                });

            modelBuilder.Entity("WebApplication1.Models.Iznajmljivanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CijenaRente")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumPodizanja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPovrata")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazivFilma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Podignut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipRezervacije")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vratio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("iznajmljivanja");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("korisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
